### ISSUE TITLE
/warden issues

### ISSUE THREAD

**Issue by bubzilla** [honkling/PrisonGame#19]
This might be stupid but when I setup a server with prison game on it and /warden it says "An internal error occurred while attempting to perform this command" and doesn't set my prefix, and armor. I kind of just need a fix for this. LOL

**Comment by bubzilla** [comment]
![image_2023-12-14_193600197](https://github.com/honkling/PrisonGame/assets/134657229/496f5fd4-3264-4a20-8a47-201ae75a7dc9)

**Comment by lilrosalyn** [comment]
give server logs and I can help you with it

**Comment by bubzilla** [comment]
k

**Comment by bubzilla** [comment]
Starting org.bukkit.craftbukkit.Main
*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://papermc.io/downloads/paper ***
System Info: Java 20 (Java HotSpot(TM) 64-Bit Server VM 20.0.2+9-78) Host: Windows 11 10.0 (amd64)
Loading libraries, please wait...
[19:44:35 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:44:35 INFO]: Found new data pack file/prison_datapack, loading it automatically
[19:44:36 INFO]: Loaded 7 recipes
[19:44:36 ERROR]: Parsing error loading custom advancement prison:skillissue: Invalid criterion trigger: minecraft:nmng
[19:44:36 ERROR]: Parsing error loading custom advancement prison:golddigger: Expected item to be an item, was unknown string 'minecraft:gold_shovel'
[19:44:37 INFO]: Starting minecraft server version 1.20.1
[19:44:37 INFO]: Loading properties
[19:44:37 INFO]: This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
[19:44:37 INFO]: Using 4 threads for Netty based IO
[19:44:37 INFO]: Server Ping Player Sample Count: 12
[19:44:37 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[19:44:37 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
[19:44:38 INFO]: Default game type: SURVIVAL
[19:44:38 INFO]: Generating keypair
[19:44:38 INFO]: Starting Minecraft server on *:25565
[19:44:38 INFO]: Using default channel type
[19:44:38 INFO]: Paper: Using Java compression from Velocity.
[19:44:38 INFO]: Paper: Using Java cipher from Velocity.
[19:44:38 INFO]: [SpigotLibraryLoader] [PrisonGame] Loading 1 libraries... please wait
[19:44:38 INFO]: [SpigotLibraryLoader] [PrisonGame] Loaded library C:\Users\bkdoe\Downloads\ShopPrison\libraries\org\jetbrains\kotlin\kotlin-stdlib-jdk8\1.9.20\kotlin-stdlib-jdk8-1.9.20.jar
[19:44:38 INFO]: [SpigotLibraryLoader] [PrisonGame] Loaded library C:\Users\bkdoe\Downloads\ShopPrison\libraries\org\jetbrains\kotlin\kotlin-stdlib\1.9.20\kotlin-stdlib-1.9.20.jar
[19:44:38 INFO]: [SpigotLibraryLoader] [PrisonGame] Loaded library C:\Users\bkdoe\Downloads\ShopPrison\libraries\org\jetbrains\annotations\13.0\annotations-13.0.jar
[19:44:38 INFO]: [SpigotLibraryLoader] [PrisonGame] Loaded library C:\Users\bkdoe\Downloads\ShopPrison\libraries\org\jetbrains\kotlin\kotlin-stdlib-jdk7\1.9.20\kotlin-stdlib-jdk7-1.9.20.jar
[19:44:38 INFO]: [LuckPerms] Loading server plugin LuckPerms v5.4.113
[19:44:38 INFO]: [Vault] Loading server plugin Vault v1.7.3-b131
[19:44:38 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.1-SNAPSHOT-673
[19:44:39 INFO]: [CustomBansPlus] Loading server plugin CustomBansPlus v3.6
[19:44:39 INFO]: [LibsDisguises] Loading server plugin LibsDisguises v10.0.40-SNAPSHOT
[19:44:39 INFO]: [FastAsyncWorldEdit] Loading server plugin FastAsyncWorldEdit v2.8.4-SNAPSHOT-625;d4b68b3
[19:44:40 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@6f28265d]
[19:44:40 INFO]: [PrisonGame] Loading server plugin PrisonGame v0.1.0
[19:44:40 INFO]: [WorldGuard] Loading server plugin WorldGuard v7.0.9+5934e49
[19:44:40 INFO]: Server permissions file permissions.yml is empty, ignoring it
[19:44:40 INFO]: [LuckPerms] Enabling LuckPerms v5.4.113
[19:44:41 INFO]:         __
[19:44:41 INFO]:   |    |__)   LuckPerms v5.4.113
[19:44:41 INFO]:   |___ |      Running on Bukkit - Paper
[19:44:41 INFO]:
[19:44:41 INFO]: [LuckPerms] Loading configuration...
[19:44:41 INFO]: [LuckPerms] Loading storage provider... [H2]
[19:44:41 INFO]: [LuckPerms] Loading internal permission managers...
[19:44:41 INFO]: [LuckPerms] Performing initial data load...
[19:44:41 INFO]: [LuckPerms] Successfully enabled. (took 1140ms)
[19:44:41 INFO]: [Vault] Enabling Vault v1.7.3-b131
[19:44:41 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[19:44:41 INFO]: [Vault] Enabled Version 1.7.3-b131
[19:44:41 INFO]: [LuckPerms] Registered Vault permission & chat hook.
[19:44:41 INFO]: [ProtocolLib] Enabling ProtocolLib v5.1.1-SNAPSHOT-673
[19:44:41 INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v2.8.4-SNAPSHOT-625;d4b68b3
[19:44:41 INFO]: [com.fastasyncworldedit.core.Fawe] LZ4 Compression Binding loaded successfully
[19:44:41 INFO]: [com.fastasyncworldedit.core.Fawe] ZSTD Compression Binding loaded successfully
[19:44:41 INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[19:44:42 INFO]: WEPIF: Vault detected! Using Vault for permissions
[19:44:42 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_20_R1.PaperweightFaweAdapter as the Bukkit adapter
[19:44:42 INFO]: Preparing level "world"
[19:44:43 INFO]: Preparing start region for dimension minecraft:overworld
[19:44:43 INFO]: Time elapsed: 160 ms
[19:44:43 INFO]: Preparing start region for dimension minecraft:the_nether
[19:44:43 INFO]: Time elapsed: 78 ms
[19:44:43 INFO]: Preparing start region for dimension minecraft:the_end
[19:44:43 INFO]: Time elapsed: 21 ms
[19:44:43 INFO]: [CustomBansPlus] Enabling CustomBansPlus v3.6
[19:44:43 INFO]: v1_20_R1
[19:44:43 INFO]: [CBP] Checking for updates...
[19:44:43 INFO]: Database Initialized.
[19:44:43 INFO]: [CustomBansPlus] Tables Initialized.
[19:44:43 INFO]: Save Cache Initiated
[19:44:43 INFO]: [LibsDisguises] Enabling LibsDisguises v10.0.40-SNAPSHOT
[19:44:43 INFO]: [LibsDisguises] File Name: LibsDisguises.jar
[19:44:43 INFO]: [LibsDisguises] Discovered nms version: v1_20_R1 (v1_20_R1)
[19:44:43 INFO]: [LibsDisguises] Jenkins Build: #1275
[19:44:43 INFO]: [LibsDisguises] Build Date: 13/12/2023 09:56
[19:44:43 INFO]: [LibsDisguises] If you own the plugin, place the premium jar downloaded from https://www.spigotmc.org/resources/libs-disguises.32453/ in plugins/LibsDisguises/
[19:44:43 INFO]: [LibsDisguises] You are running the free version, commands limited to non-players and operators. (Console, Command Blocks, Admins)
[19:44:45 INFO]: [LibsDisguises] Loaded custom disguise libraryaddict
[19:44:45 INFO]: [LibsDisguises] Loaded 1 custom disguise
[19:44:45 INFO]: [LibsDisguises] Config is up to date!
[19:44:45 INFO]: [PrisonGame] Enabling PrisonGame v0.1.0
[19:44:45 INFO]: Unknown command. Type "/help" for help.
[19:44:45 INFO]: Unknown command. Type "/help" for help.
[19:44:45 INFO]: [WorldGuard] Enabling WorldGuard v7.0.9+5934e49
[19:44:45 INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[19:44:45 INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[19:44:45 INFO]: [WorldGuard] (world) Lava fire is PERMITTED.
[19:44:45 INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[19:44:45 INFO]: [WorldGuard] Loaded configuration for world 'world'
[19:44:45 INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[19:44:45 INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[19:44:45 INFO]: [WorldGuard] (world_nether) Lava fire is PERMITTED.
[19:44:45 INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[19:44:45 INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[19:44:45 INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[19:44:45 INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[19:44:45 INFO]: [WorldGuard] (world_the_end) Lava fire is PERMITTED.
[19:44:45 INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[19:44:45 INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[19:44:45 INFO]: [WorldGuard] Loading region data...
[19:44:45 INFO]: Running delayed init tasks
[19:44:45 INFO]: [com.fastasyncworldedit.bukkit.regions.WorldGuardFeature] Plugin 'WorldGuard' found. Using it now.
[19:44:45 INFO]: [com.fastasyncworldedit.bukkit.FaweBukkit] Attempting to use plugin 'WorldGuard'
[19:44:45 INFO]: Done (8.711s)! For help, type "help"
[19:44:45 INFO]: Timings Reset
[19:44:45 INFO]: [Vault] Checking for Updates ...
[19:44:47 INFO]: [Vault] No new version available
[19:44:49 INFO]: UUID of player Shoppingberry62 is eab05061-25db-4473-888f-212d07c69461
[19:44:50 ERROR]: Could not pass event PlayerJoinEvent to PrisonGame v0.1.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.scoreboard.Team.addPlayer(org.bukkit.OfflinePlayer)" because the return value of "org.bukkit.scoreboard.Scoreboard.getTeam(String)" is null
        at prisongame.prisongame.MyListener.playerJoinignoreAsc(MyListener.java:102) ~[PrisonGame-0.1.0.jar:?]
        at prisongame.prisongame.MyListener.playerJoin(MyListener.java:107) ~[PrisonGame-0.1.0.jar:?]
        at prisongame.prisongame.listeners.PlayerJoinListener.onPlayerJoin(PlayerJoinListener.java:73) ~[PrisonGame-0.1.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor75.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:339) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:602) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1586) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[19:44:50 INFO]: Shoppingberry62 was caught and sent to prison! (JOIN)
[19:44:50 INFO]: Shoppingberry62[/127.0.0.1:55059] logged in with entity id 157 at ([world]-5.842197933905436, 1.0, -168.115232478429)
[19:44:50 ERROR]: Could not pass event PlayerAdvancementDoneEvent to PrisonGame v0.1.0
java.lang.NullPointerException: Cannot invoke "net.kyori.adventure.text.Component.color(net.kyori.adventure.text.format.TextColor)" because the return value of "org.bukkit.event.player.PlayerAdvancementDoneEvent.message()" is null
        at prisongame.prisongame.listeners.PlayerAdvancementDoneListener.onPlayerAdvancementDone(PlayerAdvancementDoneListener.java:14) ~[PrisonGame-0.1.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor97.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.PlayerAdvancements.award(PlayerAdvancements.java:246) ~[?:?]
        at net.minecraft.advancements.CriterionTrigger$Listener.run(CriterionTrigger.java:35) ~[?:?]
        at net.minecraft.advancements.critereon.SimpleCriterionTrigger.trigger(SimpleCriterionTrigger.java:73) ~[?:?]
        at net.minecraft.advancements.critereon.PlayerTrigger.trigger(PlayerTrigger.java:28) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.level.ServerPlayer.tick(ServerPlayer.java:746) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1352) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1004) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:872) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:852) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1556) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[19:44:50 INFO]: Shoppingberry62 has made the advancement [Prison But Bad]
[19:44:55 INFO]: Shoppingberry62 fell out of the world
[19:44:56 WARN]: [PrisonGame] Task #28 for PrisonGame v0.1.0 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.scoreboard.Team.addPlayer(org.bukkit.OfflinePlayer)" because the return value of "org.bukkit.scoreboard.Scoreboard.getTeam(String)" is null
        at prisongame.prisongame.MyListener.playerJoinignoreAsc(MyListener.java:102) ~[PrisonGame-0.1.0.jar:?]
        at prisongame.prisongame.MyListener.playerJoin(MyListener.java:107) ~[PrisonGame-0.1.0.jar:?]
        at prisongame.prisongame.listeners.PlayerRespawnListener.lambda$onPlayerJoin$3(PlayerRespawnListener.java:216) ~[PrisonGame-0.1.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[19:44:57 INFO]: Shoppingberry62 issued server command: /gamemode creative
[19:44:57 INFO]: [Shoppingberry62: Set own game mode to Creative Mode]
[19:45:02 INFO]: Shoppingberry62 issued server command: /warden
[19:45:02 INFO]: Shoppingberry62 has made the advancement [My Prison]
[19:45:02 INFO]: Granted the advancement [My Prison] to Shoppingberry62
[19:45:02 INFO]: Shoppingberry62 has made the advancement [Our Prison]
[19:45:02 INFO]: Granted the advancement [Our Prison] to Shoppingberry62
[19:45:02 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'warden' in plugin PrisonGame v0.1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-196]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2354) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2314) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.scoreboard.Team.addPlayer(org.bukkit.OfflinePlayer)" because the return value of "org.bukkit.scoreboard.Scoreboard.getTeam(String)" is null
        at prisongame.prisongame.commands.warden.DefaultCommand.onCommand(DefaultCommand.java:45) ~[PrisonGame-0.1.0.jar:?]
        at prisongame.prisongame.commands.WardenCommand.onCommand(WardenCommand.java:28) ~[PrisonGame-0.1.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
[19:46:07 INFO]: Shoppingberry62 issued server command: /save-all
[19:46:08 INFO]: [Shoppingberry62: Saved the game]

**Comment by bubzilla** [comment]
![taco](https://github.com/honkling/PrisonGame/assets/134657229/2a1847e8-9c24-496c-9592-da6b98c98739)

**Comment by bubzilla** [comment]
bad drawing for no reason

**Comment by lilrosalyn** [comment]
Run these commands
```
/team add Prisoners
/team add Criminals
/team add Warden
```

**Comment by bubzilla** [comment]
Thanks!
